"""add_profit_distributions

Revision ID: 0c5fe66f6754
Revises: d22d04fd3a54
Create Date: 2026-06-14 18:18:40.942107

"""
from alembic import op
import sqlalchemy as sa


revision = '0c5fe66f6754'
down_revision = 'd22d04fd3a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profit_distributions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('investor_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('distribution_date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=True),
    sa.Column('distribution_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profit_distributions')
    # ### end Alembic commands ###
