"""add_customer_to_payments

Revision ID: 2ece07d676f9
Revises: 7e05fc8ef105
Create Date: 2026-06-26 09:45:11.794771

"""
from alembic import op
import sqlalchemy as sa


revision = '2ece07d676f9'
down_revision = '7e05fc8ef105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('payments', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_column('payments', 'customer_name')
    op.drop_column('payments', 'customer_id')
    # ### end Alembic commands ###
