"""add_product_categories

Revision ID: 35d50ee99ea0
Revises: 4445c28bf226
Create Date: 2026-06-26 12:58:45.526794

"""
from alembic import op
import sqlalchemy as sa


revision = '35d50ee99ea0'
down_revision = '4445c28bf226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_organization_id'), 'product_categories', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_categories_organization_id'), table_name='product_categories')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
