"""add_pallai_with_animal_installment_ownership_vaccine_types

Revision ID: 4445c28bf226
Revises: 2ece07d676f9
Create Date: 2026-06-26 11:39:30.451779

"""
from alembic import op
import sqlalchemy as sa


revision = '4445c28bf226'
down_revision = '2ece07d676f9'
branch_labels = None
depends_on = None


def upgrade():
    # Add new enum values for OwnershipType — SQLAlchemy sends enum NAME (uppercase)
    op.execute("ALTER TYPE ownershiptype ADD VALUE IF NOT EXISTS 'PALLAI_WITH_ANIMAL'")
    op.execute("ALTER TYPE ownershiptype ADD VALUE IF NOT EXISTS 'INSTALLMENT'")
    # Also add lowercase variants (unused but harmless from earlier iteration)
    op.execute("ALTER TYPE ownershiptype ADD VALUE IF NOT EXISTS 'pallai_with_animal'")
    op.execute("ALTER TYPE ownershiptype ADD VALUE IF NOT EXISTS 'installment'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccine_types',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vaccine_types_org', 'vaccine_types', ['organization_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_vaccine_types_organization_id'), 'vaccine_types', ['organization_id'], unique=False)
    op.add_column('animals', sa.Column('pallai_customer_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'animals', 'customers', ['pallai_customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'animals', type_='foreignkey')
    op.drop_column('animals', 'pallai_customer_id')
    op.drop_index(op.f('ix_vaccine_types_organization_id'), table_name='vaccine_types')
    op.drop_index('ix_vaccine_types_org', table_name='vaccine_types')
    op.drop_table('vaccine_types')
    # ### end Alembic commands ###
