"""add_vendor_payment_method_to_milk_sales

Revision ID: 6acd93fa31b4
Revises: 7a08460645e3
Create Date: 2026-06-25 18:26:06.870300

"""
from alembic import op
import sqlalchemy as sa


revision = '6acd93fa31b4'
down_revision = '7a08460645e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milk_sales', sa.Column('vendor_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('milk_sales', sa.Column('payment_method', sa.String(length=20), nullable=True))
    op.add_column('milk_sales', sa.Column('journal_entry_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_milk_sales_vendor_id'), 'milk_sales', ['vendor_id'], unique=False)
    op.create_foreign_key(None, 'milk_sales', 'journal_entries', ['journal_entry_id'], ['id'])
    op.create_foreign_key(None, 'milk_sales', 'vendors', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milk_sales', type_='foreignkey')
    op.drop_constraint(None, 'milk_sales', type_='foreignkey')
    op.drop_index(op.f('ix_milk_sales_vendor_id'), table_name='milk_sales')
    op.drop_column('milk_sales', 'journal_entry_id')
    op.drop_column('milk_sales', 'payment_method')
    op.drop_column('milk_sales', 'vendor_id')
    # ### end Alembic commands ###
