"""add_system_settings

Revision ID: 7a08460645e3
Revises: 2e054eae792b
Create Date: 2026-06-16 16:44:35.827159

"""
from alembic import op
import sqlalchemy as sa


revision = '7a08460645e3'
down_revision = '2e054eae792b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
