"""add_customer_categories_and_customers

Revision ID: 7e05fc8ef105
Revises: 6acd93fa31b4
Create Date: 2026-06-25 19:06:38.836947

"""
from alembic import op
import sqlalchemy as sa


revision = '7e05fc8ef105'
down_revision = '6acd93fa31b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_customer_category_org_name')
    )
    op.create_index(op.f('ix_customer_categories_organization_id'), 'customer_categories', ['organization_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('cnic', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['customer_categories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_category_id'), 'customers', ['category_id'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.add_column('milk_sales', sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_index(op.f('ix_milk_sales_customer_id'), 'milk_sales', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'milk_sales', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milk_sales', type_='foreignkey')
    op.drop_index(op.f('ix_milk_sales_customer_id'), table_name='milk_sales')
    op.drop_column('milk_sales', 'customer_id')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_category_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_customer_categories_organization_id'), table_name='customer_categories')
    op.drop_table('customer_categories')
    # ### end Alembic commands ###
