"""add_inventory_product_links

Revision ID: c447b60c4355
Revises: 35d50ee99ea0
Create Date: 2026-06-30 13:42:14.077123

"""
from alembic import op
import sqlalchemy as sa


revision = 'c447b60c4355'
down_revision = '35d50ee99ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_cycles', sa.Column('seed_product_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('crop_cycles', sa.Column('seed_quantity', sa.Numeric(precision=12, scale=3), nullable=True))
    op.create_foreign_key(None, 'crop_cycles', 'products', ['seed_product_id'], ['id'])
    op.add_column('feed_types', sa.Column('inventory_product_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'feed_types', 'products', ['inventory_product_id'], ['id'])
    op.add_column('treatments', sa.Column('medicine_product_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('treatments', sa.Column('medicine_quantity', sa.Numeric(precision=10, scale=3), nullable=True))
    op.create_foreign_key(None, 'treatments', 'products', ['medicine_product_id'], ['id'])
    op.add_column('vaccinations', sa.Column('medicine_product_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('vaccinations', sa.Column('medicine_quantity', sa.Numeric(precision=10, scale=3), nullable=True))
    op.create_foreign_key(None, 'vaccinations', 'products', ['medicine_product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vaccinations', type_='foreignkey')
    op.drop_column('vaccinations', 'medicine_quantity')
    op.drop_column('vaccinations', 'medicine_product_id')
    op.drop_constraint(None, 'treatments', type_='foreignkey')
    op.drop_column('treatments', 'medicine_quantity')
    op.drop_column('treatments', 'medicine_product_id')
    op.drop_constraint(None, 'feed_types', type_='foreignkey')
    op.drop_column('feed_types', 'inventory_product_id')
    op.drop_constraint(None, 'crop_cycles', type_='foreignkey')
    op.drop_column('crop_cycles', 'seed_quantity')
    op.drop_column('crop_cycles', 'seed_product_id')
    # ### end Alembic commands ###
