"""add_subscription_id_to_invoices

Revision ID: d22d04fd3a54
Revises: 
Create Date: 2026-06-14 18:07:28.016009

"""
from alembic import op
import sqlalchemy as sa


revision = 'd22d04fd3a54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('subscription_id', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'invoices', 'pallai_subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'subscription_id')
    # ### end Alembic commands ###
