"""employee_photo_salary_history_payroll_workflow

Revision ID: d74ab38b0e2e
Revises: c447b60c4355
Create Date: 2026-07-07 14:21:12.065470

"""
from alembic import op
import sqlalchemy as sa


revision = 'd74ab38b0e2e'
down_revision = 'c447b60c4355'
branch_labels = None
depends_on = None


def upgrade():
    # Add SUBMITTED value to payrollstatus enum (SQLAlchemy sends .name = uppercase)
    op.execute("ALTER TYPE payrollstatus ADD VALUE IF NOT EXISTS 'SUBMITTED'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_salary_history',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employee_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('salary_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('previous_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('change_reason', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_salary_history_employee_id'), 'employee_salary_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_salary_history_organization_id'), 'employee_salary_history', ['organization_id'], unique=False)
    op.add_column('employees', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('payroll_runs', sa.Column('submitted_by', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('payroll_runs', sa.Column('paid_by', sa.UUID(as_uuid=False), nullable=True))
    op.create_foreign_key(None, 'payroll_runs', 'users', ['submitted_by'], ['id'])
    op.create_foreign_key(None, 'payroll_runs', 'users', ['paid_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payroll_runs', type_='foreignkey')
    op.drop_constraint(None, 'payroll_runs', type_='foreignkey')
    op.drop_column('payroll_runs', 'paid_by')
    op.drop_column('payroll_runs', 'submitted_by')
    op.drop_column('employees', 'photo_url')
    op.drop_index(op.f('ix_employee_salary_history_organization_id'), table_name='employee_salary_history')
    op.drop_index(op.f('ix_employee_salary_history_employee_id'), table_name='employee_salary_history')
    op.drop_table('employee_salary_history')
    # ### end Alembic commands ###
